### PR TITLE
Target build asset for the Buildpack when using the environment variable

### PR DESCRIPTION
**Pull request by shahulsonhal**
We have a Buildpacke e2e test in the [ shipwright-io/build](https://github.com/shipwright-io/build) repo that sets the [`BP_GO_TARGETS`](https://github.com/paketo-buildpacks/go-build#bp_go_targets) environment variable.

**Note: See [here](https://github.com/shipwright-io/build/pull/906/files#diff-d5d12b6ea07b0a78c9ad1987e1486c565ecf16839f77a93e91b09475cf6c0e99R261-R281) the test case that uses the introduced changes.**

### CODE REVIEW

**Review by SaschaSchwarze0 — APPROVED** [review]
/lgtm
/approve

**Comment by SaschaSchwarze0** [comment]
/assign@adambkaplan

@adambkaplan the approve (and maybe automatic merge) still does not work here.

**Review by SaschaSchwarze0 — CHANGES_REQUESTED** [review]
Sry, just noticed your directory structure. I think this needs to change. Imo building with contextDir=source-build without `BP_GO_TARGETS` will work because there is a main.go inside source-build. But we want a build config that fails if the env var is no set. So, imo you need to move it to a new directory, like `/source-build-with-package/main-package`

**Review by SaschaSchwarze0 — APPROVED** [review]
/lgtm
/approve

**Review by adambkaplan — APPROVED** [review]
/approve

**Comment by adambkaplan** [comment]
Green button merging - looks like this was not fully integrated with OpenShift's CI system (which provides all of the prow commands and tide integration).

**Pull request merged**
