### PR TITLE
Use base images in ghcr.io

### PR DESCRIPTION
**Pull request by imjasonh**
https://github.com/shipwright-io/build/issues/913

See image: https://ghcr.io/shipwright-io/shipwright-samples/golang:1.16

### CODE REVIEW

**Review by otaviof — APPROVED** [review]
/lgtm

**Review by SaschaSchwarze0 — APPROVED** [review]
/approve

**Review by adambkaplan — APPROVED** [review]
/approve

**Comment by adambkaplan** [comment]
Green button merging.

**Pull request merged**
